/* DECORATIONS — MH Wilds. Source: user-provided Decorations spreadsheet (361 jewels, incl. dual-skill).
   Schema: { id, name, skill, lv, [skill2, lv2], slot, rarity, type }
   Slot rule: a slot of level N accepts any decoration of slot ≤ N. */

var DECORATIONS = [
  { id:'adapt-1', name:'Adapt Jewel [1]', skill:'Adaptability', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'antiblast-1', name:'Antiblast Jewel [1]', skill:'Blast Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'antidote-1', name:'Antidote Jewel [1]', skill:'Poison Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'antipara-1', name:'Antipara Jewel [1]', skill:'Paralysis Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'bomber-1', name:'Bomber Jewel [1]', skill:'Bombardier', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'botany-1', name:'Botany Jewel [1]', skill:'Botanist', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'brace-1', name:'Brace Jewel [1]', skill:'Flinch Free', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'climber-1', name:'Climber Jewel [1]', skill:'Cliffhanger', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'def-lock-1', name:'Def Lock Jewel [1]', skill:'Iron Skin', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'defense-1', name:'Defense Jewel [1]', skill:'Defense Boost', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'dive-1', name:'Dive Jewel [1]', skill:'Leap of Faith', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'dragon-res-1', name:'Dragon Res Jewel [1]', skill:'Dragon Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'enduring-1', name:'Enduring Jewel [1]', skill:'Item Prolonger', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'escape-1', name:'Escape Jewel [1]', skill:'Bind Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'fire-res-1', name:'Fire Res Jewel [1]', skill:'Fire Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'flash-1', name:'Flash Jewel [1]', skill:'Blindsider', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'footing-1', name:'Footing Jewel [1]', skill:'Tremor Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'friendship-1', name:'Friendship Jewel [1]', skill:'Wide-Range', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'geology-1', name:'Geology Jewel [1]', skill:'Geologist', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'gobbler-1', name:'Gobbler Jewel [1]', skill:'Speed Eating', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'growth-1', name:'Growth Jewel [1]', skill:'Self-Improvement', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'hungerless-1', name:'Hungerless Jewel [1]', skill:'Hunger Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'ice-res-1', name:'Ice Res Jewel [1]', skill:'Ice Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'intimidator-1', name:'Intimidator Jewel [1]', skill:'Intimidator', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'leap-1', name:'Leap Jewel [1]', skill:'Jump Master', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'medicine-1', name:'Medicine Jewel [1]', skill:'Recovery Up', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'mirewalker-1', name:'Mirewalker Jewel [1]', skill:'Aquatic-Oilsilt Mobility', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'pep-1', name:'Pep Jewel [1]', skill:'Sleep Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'perfume-1', name:'Perfume Jewel [1]', skill:'Stench Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'physique-1', name:'Physique Jewel [1]', skill:'Constitution', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'protection-1', name:'Protection Jewel [1]', skill:'Divine Blessing', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'ranger-1', name:'Ranger Jewel [1]', skill:'Outdoorsman', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'recovery-1', name:'Recovery Jewel [1]', skill:'Recovery Speed', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'sane-1', name:'Sane Jewel [1]', skill:'Antivirus', lv:1, slot:1, rarity:5, type:'armor' },
  { id:'satiated-1', name:'Satiated Jewel [1]', skill:'Free Meal', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'sheath-1', name:'Sheath Jewel [1]', skill:'Quick Sheathe', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'shockproof-1', name:'Shockproof Jewel [1]', skill:'Shock Absorber', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'specimen-1', name:'Specimen Jewel [1]', skill:'Entomologist', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'sprinter-1', name:'Sprinter Jewel [1]', skill:'Marathon Runner', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'steadfast-1', name:'Steadfast Jewel [1]', skill:'Stun Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'survival-1', name:'Survival Jewel [1]', skill:'Survival Expert', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'suture-1', name:'Suture Jewel [1]', skill:'Bleeding Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'thunder-res-1', name:'Thunder Res Jewel [1]', skill:'Thunder Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'water-res-1', name:'Water Res Jewel [1]', skill:'Water Resistance', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'wind-resist-1', name:'Wind Resist Jewel [1]', skill:'Windproof', lv:1, slot:1, rarity:3, type:'armor' },
  { id:'ambush-2', name:'Ambush Jewel [2]', skill:'Ambush', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'counter-2', name:'Counter Jewel [2]', skill:'Counterstrike', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'destroyer-2', name:'Destroyer Jewel [2]', skill:'Partbreaker', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'earplugs-2', name:'Earplugs Jewel [2]', skill:'Earplugs', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'evasion-2', name:'Evasion Jewel [2]', skill:'Evade Window', lv:2, slot:2, rarity:5, type:'armor' },
  { id:'flawless-2', name:'Flawless Jewel [2]', skill:'Peak Performance', lv:2, slot:2, rarity:4, type:'armor' },
  { id:'fungiform-2', name:'Fungiform Jewel [2]', skill:'Mushroomancer', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'furor-2', name:'Furor Jewel [2]', skill:'Resentment', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'jumping-2', name:'Jumping Jewel [2]', skill:'Evade Extender', lv:2, slot:2, rarity:4, type:'armor' },
  { id:'maintenance-2', name:'Maintenance Jewel [2]', skill:'Tool Specialist', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'mighty-2', name:'Mighty Jewel [2]', skill:'Maximum Might', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'phoenix-2', name:'Phoenix Jewel [2]', skill:'Coalescence', lv:1, slot:2, rarity:7, type:'armor' },
  { id:'potential-2', name:'Potential Jewel [2]', skill:'Heroics', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'refresh-2', name:'Refresh Jewel [2]', skill:'Stamina Surge', lv:1, slot:2, rarity:4, type:'armor' },
  { id:'chain-3', name:'Chain Jewel [3]', skill:'Burst', lv:1, slot:3, rarity:5, type:'armor' },
  { id:'challenger-3', name:'Challenger Jewel [3]', skill:'Agitator', lv:1, slot:3, rarity:5, type:'armor' },
  { id:'counterattack-3', name:'Counterattack Jewel [3]', skill:'Adrenaline Rush', lv:1, slot:3, rarity:5, type:'armor' },
  { id:'flayer-3', name:'Flayer Jewel [3]', skill:'Flayer', lv:1, slot:3, rarity:5, type:'armor' },
  { id:'foray-3', name:'Foray Jewel [3]', skill:'Foray', lv:1, slot:3, rarity:5, type:'armor' },
  { id:'tenderizer-3', name:'Tenderizer Jewel [3]', skill:'Weakness Exploit', lv:1, slot:3, rarity:5, type:'armor' },
  { id:'throttle-3', name:'Throttle Jewel [3]', skill:'Latent Power', lv:1, slot:3, rarity:5, type:'armor' },
  { id:'artillery-1', name:'Artillery Jewel [1]', skill:'Artillery', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'attack-1', name:'Attack Jewel [1]', skill:'Attack Boost', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'bandolier-1', name:'Bandolier Jewel [1]', skill:'Tetrad Shot', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'blast-1', name:'Blast Jewel [1]', skill:'Blast Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'blaze-1', name:'Blaze Jewel [1]', skill:'Fire Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'blunt-1', name:'Blunt Jewel [1]', skill:'Bludgeoner', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'bolt-1', name:'Bolt Jewel [1]', skill:'Thunder Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'charge-1', name:'Charge Jewel [1]', skill:'Charge Master', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'crit-element-1', name:'Crit Element Jewel [1]', skill:'Critical Element', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'crit-status-1', name:'Crit Status Jewel [1]', skill:'Critical Status', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'critical-1', name:'Critical Jewel [1]', skill:'Critical Boost', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'dragon-1', name:'Dragon Jewel [1]', skill:'Dragon Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'drain-1', name:'Drain Jewel [1]', skill:'Stamina Thief', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'draw-1', name:'Draw Jewel [1]', skill:'Critical Draw', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'enhancer-1', name:'Enhancer Jewel [1]', skill:'Power Prolonger', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'expert-1', name:'Expert Jewel [1]', skill:'Critical Eye', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'focus-1', name:'Focus Jewel [1]', skill:'Focus', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'frost-1', name:'Frost Jewel [1]', skill:'Ice Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'gambit-1', name:'Gambit Jewel [1]', skill:'Punishing Draw', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'grinder-1', name:'Grinder Jewel [1]', skill:'Speed Sharpening', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'guardian-1', name:'Guardian Jewel [1]', skill:'Offensive Guard', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'handicraft-1', name:'Handicraft Jewel [1]', skill:'Handicraft', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'ironwall-1', name:'Ironwall Jewel [1]', skill:'Guard', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'ko-1', name:'KO Jewel [1]', skill:'Slugger', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'magazine-1', name:'Magazine Jewel [1]', skill:'Load Shells', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'mind-s-eye-1', name:'Mind\'s Eye Jewel [1]', skill:'Mind\'s Eye', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'opener-1', name:'Opener Jewel [1]', skill:'Opening Shot', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'paralyzer-1', name:'Paralyzer Jewel [1]', skill:'Paralysis Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'precise-1', name:'Precise Jewel [1]', skill:'Ballistics', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'quickswitch-1', name:'Quickswitch Jewel [1]', skill:'Rapid Morph', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'razor-sharp-1', name:'Razor Sharp Jewel [1]', skill:'Razor Sharp', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'sharp-1', name:'Sharp Jewel [1]', skill:'Protective Polish', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'shield-1', name:'Shield Jewel [1]', skill:'Guard Up', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'sleep-1', name:'Sleep Jewel [1]', skill:'Sleep Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'stream-1', name:'Stream Jewel [1]', skill:'Water Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'trueshot-1', name:'Trueshot Jewel [1]', skill:'Special Ammo Boost', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'venom-1', name:'Venom Jewel [1]', skill:'Poison Attack', lv:1, slot:1, rarity:3, type:'weapon' },
  { id:'artillery-2', name:'Artillery Jewel [2]', skill:'Artillery', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'attack-2', name:'Attack Jewel [2]', skill:'Attack Boost', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'bandolier-2', name:'Bandolier Jewel [2]', skill:'Tetrad Shot', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'blast-2', name:'Blast Jewel [2]', skill:'Blast Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'blastcoat-2', name:'Blastcoat Jewel [2]', skill:'Blast Functionality', lv:1, slot:2, rarity:4, type:'weapon' },
  { id:'blaze-2', name:'Blaze Jewel [2]', skill:'Fire Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'blunt-2', name:'Blunt Jewel [2]', skill:'Bludgeoner', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'bolt-2', name:'Bolt Jewel [2]', skill:'Thunder Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'charge-2', name:'Charge Jewel [2]', skill:'Charge Master', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'charge-up-2', name:'Charge Up Jewel [2]', skill:'Charge Up', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'crit-element-2', name:'Crit Element Jewel [2]', skill:'Critical Element', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'crit-status-2', name:'Crit Status Jewel [2]', skill:'Critical Status', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'critical-2', name:'Critical Jewel [2]', skill:'Critical Boost', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'dragon-2', name:'Dragon Jewel [2]', skill:'Dragon Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'drain-2', name:'Drain Jewel [2]', skill:'Stamina Thief', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'draincoat-2', name:'Draincoat Jewel [2]', skill:'Exhaust Functionality', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'draw-2', name:'Draw Jewel [2]', skill:'Critical Draw', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'enhancer-2', name:'Enhancer Jewel [2]', skill:'Power Prolonger', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'expert-2', name:'Expert Jewel [2]', skill:'Critical Eye', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'flight-2', name:'Flight Jewel [2]', skill:'Airborne', lv:1, slot:2, rarity:4, type:'weapon' },
  { id:'focus-2', name:'Focus Jewel [2]', skill:'Focus', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'frost-2', name:'Frost Jewel [2]', skill:'Ice Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'gambit-2', name:'Gambit Jewel [2]', skill:'Punishing Draw', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'grinder-2', name:'Grinder Jewel [2]', skill:'Speed Sharpening', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'guardian-2', name:'Guardian Jewel [2]', skill:'Offensive Guard', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'handicraft-2', name:'Handicraft Jewel [2]', skill:'Handicraft', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'ironwall-2', name:'Ironwall Jewel [2]', skill:'Guard', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'ko-2', name:'KO Jewel [2]', skill:'Slugger', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'magazine-2', name:'Magazine Jewel [2]', skill:'Load Shells', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'mind-s-eye-2', name:'Mind\'s Eye Jewel [2]', skill:'Mind\'s Eye', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'opener-2', name:'Opener Jewel [2]', skill:'Opening Shot', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'paralyzer-2', name:'Paralyzer Jewel [2]', skill:'Paralysis Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'poison-2', name:'Poison Jewel [2]', skill:'Poison Duration Up', lv:2, slot:2, rarity:5, type:'weapon' },
  { id:'poisoncoat-2', name:'Poisoncoat Jewel [2]', skill:'Poison Functionality', lv:1, slot:2, rarity:4, type:'weapon' },
  { id:'precise-2', name:'Precise Jewel [2]', skill:'Ballistics', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'quickswitch-2', name:'Quickswitch Jewel [2]', skill:'Rapid Morph', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'razor-sharp-2', name:'Razor Sharp Jewel [2]', skill:'Razor Sharp', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'sharp-2', name:'Sharp Jewel [2]', skill:'Protective Polish', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'shield-2', name:'Shield Jewel [2]', skill:'Guard Up', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'sleep-2', name:'Sleep Jewel [2]', skill:'Sleep Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'sonorous-2', name:'Sonorous Jewel [2]', skill:'Horn Maestro', lv:1, slot:2, rarity:4, type:'weapon' },
  { id:'stream-2', name:'Stream Jewel [2]', skill:'Water Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'trueshot-2', name:'Trueshot Jewel [2]', skill:'Special Ammo Boost', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'venom-2', name:'Venom Jewel [2]', skill:'Poison Attack', lv:2, slot:2, rarity:4, type:'weapon' },
  { id:'artillery-3', name:'Artillery Jewel [3]', skill:'Artillery', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'attack-3', name:'Attack Jewel [3]', skill:'Attack Boost', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'bandolier-3', name:'Bandolier Jewel [3]', skill:'Tetrad Shot', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'blast-3', name:'Blast Jewel [3]', skill:'Blast Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'blaze-3', name:'Blaze Jewel [3]', skill:'Fire Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'blunt-3', name:'Blunt Jewel [3]', skill:'Bludgeoner', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'bolt-3', name:'Bolt Jewel [3]', skill:'Thunder Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'charge-3', name:'Charge Jewel [3]', skill:'Charge Master', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'crit-elem-3', name:'Crit Elem Jewel [3]', skill:'Critical Element', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'crit-stat-3', name:'Crit Stat Jewel [3]', skill:'Critical Status', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'critical-3', name:'Critical Jewel [3]', skill:'Critical Boost', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'dragon-3', name:'Dragon Jewel [3]', skill:'Dragon Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'drain-3', name:'Drain Jewel [3]', skill:'Stamina Thief', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'draw-3', name:'Draw Jewel [3]', skill:'Critical Draw', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'enhancer-3', name:'Enhancer Jewel [3]', skill:'Power Prolonger', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'expert-3', name:'Expert Jewel [3]', skill:'Critical Eye', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'focus-3', name:'Focus Jewel [3]', skill:'Focus', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'forceshot-3', name:'Forceshot Jewel [3]', skill:'Normal Shots', lv:1, slot:3, rarity:5, type:'weapon' },
  { id:'frost-3', name:'Frost Jewel [3]', skill:'Ice Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'gambit-3', name:'Gambit Jewel [3]', skill:'Punishing Draw', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'guardian-3', name:'Guardian Jewel [3]', skill:'Offensive Guard', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'handicraft-3', name:'Handicraft Jewel [3]', skill:'Handicraft', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'ironwall-3', name:'Ironwall Jewel [3]', skill:'Guard', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'ko-3', name:'KO Jewel [3]', skill:'Slugger', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'mastery-3', name:'Mastery Jewel [3]', skill:'Master\'s Touch', lv:1, slot:3, rarity:5, type:'weapon' },
  { id:'mind-s-eye-3', name:'Mind\'s Eye Jewel [3]', skill:'Mind\'s Eye', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'opener-3', name:'Opener Jewel [3]', skill:'Opening Shot', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'paracoat-3', name:'Paracoat Jewel [3]', skill:'Para Functionality', lv:1, slot:3, rarity:5, type:'weapon' },
  { id:'paralyzer-3', name:'Paralyzer Jewel [3]', skill:'Paralysis Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'pierce-3', name:'Pierce Jewel [3]', skill:'Piercing Shots', lv:1, slot:3, rarity:5, type:'weapon' },
  { id:'precise-3', name:'Precise Jewel [3]', skill:'Ballistics', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'quickswitch-3', name:'Quickswitch Jewel [3]', skill:'Rapid Morph', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'rzr-sharp-3', name:'Rzr Sharp Jewel [3]', skill:'Razor Sharp', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'salvo-3', name:'Salvo Jewel [3]', skill:'Rapid Fire Up', lv:1, slot:3, rarity:5, type:'weapon' },
  { id:'sharp-3', name:'Sharp Jewel [3]', skill:'Protective Polish', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'shield-3', name:'Shield Jewel [3]', skill:'Guard Up', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'sleep-3', name:'Sleep Jewel [3]', skill:'Sleep Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'sleepcoat-3', name:'Sleepcoat Jewel [3]', skill:'Sleep Functionality', lv:1, slot:3, rarity:5, type:'weapon' },
  { id:'spread-3', name:'Spread Jewel [3]', skill:'Spread-Power Shots', lv:1, slot:3, rarity:5, type:'weapon' },
  { id:'stream-3', name:'Stream Jewel [3]', skill:'Water Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'venom-3', name:'Venom Jewel [3]', skill:'Poison Attack', lv:3, slot:3, rarity:5, type:'weapon' },
  { id:'bandolier-blaze-3', name:'Bandolier-Blaze Jewel [3]', skill:'Tetrad Shot', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'bandolier-bolt-3', name:'Bandolier-Bolt Jewel [3]', skill:'Tetrad Shot', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'bandolier-dragon-3', name:'Bandolier-Dragon Jewel [3]', skill:'Tetrad Shot', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'bandolier-frost-3', name:'Bandolier-Frost Jewel [3]', skill:'Tetrad Shot', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'bandolier-ironwall-3', name:'Bandolier-Ironwall Jewel [3]', skill:'Tetrad Shot', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'bandolier-precise-3', name:'Bandolier-Precise Jewel [3]', skill:'Tetrad Shot', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'bandolier-stream-3', name:'Bandolier-Stream Jewel [3]', skill:'Tetrad Shot', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'blaze-bandolier-3', name:'Blaze-Bandolier Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Tetrad Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-crit-elem-3', name:'Blaze-Crit Elem Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Critical Element', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-enhancer-3', name:'Blaze-Enhancer Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Power Prolonger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-focus-3', name:'Blaze-Focus Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Focus', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-guardian-3', name:'Blaze-Guardian Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Offensive Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-handicraft-3', name:'Blaze-Handicraft Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-ironwall-3', name:'Blaze-Ironwall Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-ko-3', name:'Blaze-KO Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-opener-3', name:'Blaze-Opener Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Opening Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-precise-3', name:'Blaze-Precise Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-quickswitch-3', name:'Blaze-Quickswitch Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Rapid Morph', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-rzr-sharp-3', name:'Blaze-Rzr Sharp Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Razor Sharp', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'blaze-shield-3', name:'Blaze-Shield Jewel [3]', skill:'Fire Attack', lv:3, skill2:'Guard Up', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-bandolier-3', name:'Bolt-Bandolier Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Tetrad Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-crit-elem-3', name:'Bolt-Crit Elem Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Critical Element', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-enhancer-3', name:'Bolt-Enhancer Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Power Prolonger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-focus-3', name:'Bolt-Focus Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Focus', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-guardian-3', name:'Bolt-Guardian Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Offensive Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-handicraft-3', name:'Bolt-Handicraft Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-ironwall-3', name:'Bolt-Ironwall Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-ko-3', name:'Bolt-KO Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-opener-3', name:'Bolt-Opener Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Opening Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-precise-3', name:'Bolt-Precise Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-quickswitch-3', name:'Bolt-Quickswitch Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Rapid Morph', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-rzr-sharp-3', name:'Bolt-Rzr Sharp Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Razor Sharp', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'bolt-shield-3', name:'Bolt-Shield Jewel [3]', skill:'Thunder Attack', lv:3, skill2:'Guard Up', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'charge-up-attack-3', name:'Charge Up-Attack Jewel [3]', skill:'Charge Up', lv:1, skill2:'Attack Boost', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'charge-up-draw-3', name:'Charge Up-Draw Jewel [3]', skill:'Charge Up', lv:1, skill2:'Critical Draw', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'charge-up-expert-3', name:'Charge Up-Expert Jewel [3]', skill:'Charge Up', lv:1, skill2:'Critical Eye', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'charge-up-handicraft-3', name:'Charge Up-Handicraft Jewel [3]', skill:'Charge Up', lv:1, skill2:'Handicraft', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'charge-up-ko-3', name:'Charge Up-KO Jewel [3]', skill:'Charge Up', lv:1, skill2:'Slugger', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'charge-handicraft-3', name:'Charge-Handicraft Jewel [3]', skill:'Charge Master', lv:1, skill2:'Handicraft', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'charge-ko-3', name:'Charge-KO Jewel [3]', skill:'Charge Master', lv:1, skill2:'Slugger', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'crit-elem-blaze-3', name:'Crit Elem-Blaze Jewel [3]', skill:'Critical Element', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-elem-bolt-3', name:'Crit Elem-Bolt Jewel [3]', skill:'Critical Element', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-elem-dragon-3', name:'Crit Elem-Dragon Jewel [3]', skill:'Critical Element', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-elem-frost-3', name:'Crit Elem-Frost Jewel [3]', skill:'Critical Element', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-elem-handicraft-3', name:'Crit Elem-Handicraft Jewel [3]', skill:'Critical Element', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-elem-ironwall-3', name:'Crit Elem-Ironwall Jewel [3]', skill:'Critical Element', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-elem-ko-3', name:'Crit Elem-KO Jewel [3]', skill:'Critical Element', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-elem-stream-3', name:'Crit Elem-Stream Jewel [3]', skill:'Critical Element', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'crit-element-precise-3', name:'Crit Element-Precise Jewel [3]', skill:'Critical Element', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'crit-stat-handicraft-3', name:'Crit Stat-Handicraft Jewel [3]', skill:'Critical Status', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'crit-stat-ironwall-3', name:'Crit Stat-Ironwall Jewel [3]', skill:'Critical Status', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'crit-stat-precise-3', name:'Crit Stat-Precise Jewel [3]', skill:'Critical Status', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'crit-status-ko-3', name:'Crit Status-KO Jewel [3]', skill:'Critical Status', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-bandolier-3', name:'Dragon-Bandolier Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Tetrad Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-crit-elem-3', name:'Dragon-Crit Elem Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Critical Element', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-enhancer-3', name:'Dragon-Enhancer Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Power Prolonger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-focus-3', name:'Dragon-Focus Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Focus', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-guardian-3', name:'Dragon-Guardian Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Offensive Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-handicraft-3', name:'Dragon-Handicraft Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-ironwall-3', name:'Dragon-Ironwall Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-ko-3', name:'Dragon-KO Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-opener-3', name:'Dragon-Opener Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Opening Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-precise-3', name:'Dragon-Precise Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-quickswitch-3', name:'Dragon-Quickswitch Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Rapid Morph', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-rzr-sharp-3', name:'Dragon-Rzr Sharp Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Razor Sharp', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'dragon-shield-3', name:'Dragon-Shield Jewel [3]', skill:'Dragon Attack', lv:3, skill2:'Guard Up', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'enhancer-blaze-3', name:'Enhancer-Blaze Jewel [3]', skill:'Power Prolonger', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'enhancer-bolt-3', name:'Enhancer-Bolt Jewel [3]', skill:'Power Prolonger', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'enhancer-dragon-3', name:'Enhancer-Dragon Jewel [3]', skill:'Power Prolonger', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'enhancer-frost-3', name:'Enhancer-Frost Jewel [3]', skill:'Power Prolonger', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'enhancer-handicraft-3', name:'Enhancer-Handicraft Jewel [3]', skill:'Power Prolonger', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'enhancer-stream-3', name:'Enhancer-Stream Jewel [3]', skill:'Power Prolonger', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'flight-attack-3', name:'Flight-Attack Jewel [3]', skill:'Airborne', lv:1, skill2:'Attack Boost', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'flight-draw-3', name:'Flight-Draw Jewel [3]', skill:'Airborne', lv:1, skill2:'Critical Draw', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'flight-expert-3', name:'Flight-Expert Jewel [3]', skill:'Airborne', lv:1, skill2:'Critical Eye', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'flight-handicraft-3', name:'Flight-Handicraft Jewel [3]', skill:'Airborne', lv:1, skill2:'Handicraft', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'focus-blaze-3', name:'Focus-Blaze Jewel [3]', skill:'Focus', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'focus-bolt-3', name:'Focus-Bolt Jewel [3]', skill:'Focus', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'focus-dragon-3', name:'Focus-Dragon Jewel [3]', skill:'Focus', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'focus-frost-3', name:'Focus-Frost Jewel [3]', skill:'Focus', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'focus-handicraft-3', name:'Focus-Handicraft Jewel [3]', skill:'Focus', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'focus-ko-3', name:'Focus-KO Jewel [3]', skill:'Focus', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'focus-precise-3', name:'Focus-Precise Jewel [3]', skill:'Focus', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'focus-stream-3', name:'Focus-Stream Jewel [3]', skill:'Focus', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'frost-bandolier-3', name:'Frost-Bandolier Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Tetrad Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-crit-elem-3', name:'Frost-Crit Elem Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Critical Element', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-enhancer-3', name:'Frost-Enhancer Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Power Prolonger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-focus-3', name:'Frost-Focus Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Focus', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-guardian-3', name:'Frost-Guardian Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Offensive Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-handicraft-3', name:'Frost-Handicraft Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-ironwall-3', name:'Frost-Ironwall Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-ko-3', name:'Frost-KO Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-opener-3', name:'Frost-Opener Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Opening Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-precise-3', name:'Frost-Precise Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-quickswitch-3', name:'Frost-Quickswitch Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Rapid Morph', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-rzr-sharp-3', name:'Frost-Rzr Sharp Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Razor Sharp', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'frost-shield-3', name:'Frost-Shield Jewel [3]', skill:'Ice Attack', lv:3, skill2:'Guard Up', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'gambit-handicraft-3', name:'Gambit-Handicraft Jewel [3]', skill:'Punishing Draw', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'gambit-ironwall-3', name:'Gambit-Ironwall Jewel [3]', skill:'Punishing Draw', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'gambit-ko-3', name:'Gambit-KO Jewel [3]', skill:'Punishing Draw', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'grinder-attack-3', name:'Grinder-Attack Jewel [3]', skill:'Speed Sharpening', lv:2, skill2:'Attack Boost', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'grinder-draw-3', name:'Grinder-Draw Jewel [3]', skill:'Speed Sharpening', lv:2, skill2:'Critical Draw', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'grinder-expert-3', name:'Grinder-Expert Jewel [3]', skill:'Speed Sharpening', lv:2, skill2:'Critical Eye', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'grinder-handicraft-3', name:'Grinder-Handicraft Jewel [3]', skill:'Speed Sharpening', lv:2, skill2:'Handicraft', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'grinder-ironwall-3', name:'Grinder-Ironwall Jewel [3]', skill:'Speed Sharpening', lv:2, skill2:'Guard', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'grinder-ko-3', name:'Grinder-KO Jewel [3]', skill:'Speed Sharpening', lv:2, skill2:'Slugger', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'guardian-blaze-3', name:'Guardian-Blaze Jewel [3]', skill:'Offensive Guard', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'guardian-bolt-3', name:'Guardian-Bolt Jewel [3]', skill:'Offensive Guard', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'guardian-dragon-3', name:'Guardian-Dragon Jewel [3]', skill:'Offensive Guard', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'guardian-frost-3', name:'Guardian-Frost Jewel [3]', skill:'Offensive Guard', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'guardian-handicraft-3', name:'Guardian-Handicraft Jewel [3]', skill:'Offensive Guard', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'guardian-ironwall-3', name:'Guardian-Ironwall Jewel [3]', skill:'Offensive Guard', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'guardian-stream-3', name:'Guardian-Stream Jewel [3]', skill:'Offensive Guard', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'magazine-attack-3', name:'Magazine-Attack Jewel [3]', skill:'Load Shells', lv:2, skill2:'Attack Boost', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'magazine-draw-3', name:'Magazine-Draw Jewel [3]', skill:'Load Shells', lv:2, skill2:'Critical Draw', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'magazine-expert-3', name:'Magazine-Expert Jewel [3]', skill:'Load Shells', lv:2, skill2:'Critical Eye', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'magazine-handicraft-3', name:'Magazine-Handicraft Jewel [3]', skill:'Load Shells', lv:2, skill2:'Handicraft', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'magazine-ironwall-3', name:'Magazine-Ironwall Jewel [3]', skill:'Load Shells', lv:2, skill2:'Guard', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'opener-blaze-3', name:'Opener-Blaze Jewel [3]', skill:'Opening Shot', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'opener-bolt-3', name:'Opener-Bolt Jewel [3]', skill:'Opening Shot', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'opener-dragon-3', name:'Opener-Dragon Jewel [3]', skill:'Opening Shot', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'opener-frost-3', name:'Opener-Frost Jewel [3]', skill:'Opening Shot', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'opener-ironwall-3', name:'Opener-Ironwall Jewel [3]', skill:'Opening Shot', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'opener-precise-3', name:'Opener-Precise Jewel [3]', skill:'Opening Shot', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'opener-stream-3', name:'Opener-Stream Jewel [3]', skill:'Opening Shot', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'poison-attack-3', name:'Poison-Attack Jewel [3]', skill:'Poison Duration Up', lv:1, skill2:'Attack Boost', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'poison-draw-3', name:'Poison-Draw Jewel [3]', skill:'Poison Duration Up', lv:1, skill2:'Critical Draw', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'poison-expert-3', name:'Poison-Expert Jewel [3]', skill:'Poison Duration Up', lv:1, skill2:'Critical Eye', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'poison-handicraft-3', name:'Poison-Handicraft Jewel [3]', skill:'Poison Duration Up', lv:1, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'poison-ironwall-3', name:'Poison-Ironwall Jewel [3]', skill:'Poison Duration Up', lv:1, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'poison-ko-3', name:'Poison-KO Jewel [3]', skill:'Poison Duration Up', lv:1, skill2:'Slugger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'poison-precise-3', name:'Poison-Precise Jewel [3]', skill:'Poison Duration Up', lv:1, skill2:'Ballistics', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'quickswitch-blaze-3', name:'Quickswitch-Blaze Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'quickswitch-bolt-3', name:'Quickswitch-Bolt Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'quickswitch-dragon-3', name:'Quickswitch-Dragon Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'quickswitch-frost-3', name:'Quickswitch-Frost Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'quickswitch-handicraft-3', name:'Quickswitch-Handicraft Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'quickswitch-ironwall-3', name:'Quickswitch-Ironwall Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'quickswitch-ko-3', name:'Quickswitch-KO Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'quickswitch-stream-3', name:'Quickswitch-Stream Jewel [3]', skill:'Rapid Morph', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'razor-sharp-ko-3', name:'Razor Sharp-KO Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'rzr-sharp-blaze-3', name:'Rzr Sharp-Blaze Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'rzr-sharp-bolt-3', name:'Rzr Sharp-Bolt Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'rzr-sharp-dragon-3', name:'Rzr Sharp-Dragon Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'rzr-sharp-frost-3', name:'Rzr Sharp-Frost Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'rzr-sharp-handicraft-3', name:'Rzr Sharp-Handicraft Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'rzr-sharp-ironwall-3', name:'Rzr Sharp-Ironwall Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'rzr-sharp-stream-3', name:'Rzr Sharp-Stream Jewel [3]', skill:'Razor Sharp', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:7, type:'weapon' },
  { id:'shield-blaze-3', name:'Shield-Blaze Jewel [3]', skill:'Guard Up', lv:3, skill2:'Fire Attack', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'shield-bolt-3', name:'Shield-Bolt Jewel [3]', skill:'Guard Up', lv:3, skill2:'Thunder Attack', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'shield-dragon-3', name:'Shield-Dragon Jewel [3]', skill:'Guard Up', lv:3, skill2:'Dragon Attack', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'shield-frost-3', name:'Shield-Frost Jewel [3]', skill:'Guard Up', lv:3, skill2:'Ice Attack', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'shield-handicraft-3', name:'Shield-Handicraft Jewel [3]', skill:'Guard Up', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'shield-ironwall-3', name:'Shield-Ironwall Jewel [3]', skill:'Guard Up', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'shield-stream-3', name:'Shield-Stream Jewel [3]', skill:'Guard Up', lv:3, skill2:'Water Attack', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'sonorous-attack-3', name:'Sonorous-Attack Jewel [3]', skill:'Horn Maestro', lv:2, skill2:'Attack Boost', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'sonorous-draw-3', name:'Sonorous-Draw Jewel [3]', skill:'Horn Maestro', lv:2, skill2:'Critical Draw', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'sonorous-expert-3', name:'Sonorous-Expert Jewel [3]', skill:'Horn Maestro', lv:2, skill2:'Critical Eye', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'sonorous-handicraft-3', name:'Sonorous-Handicraft Jewel [3]', skill:'Horn Maestro', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'sonorous-ko-3', name:'Sonorous-KO Jewel [3]', skill:'Horn Maestro', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:5, type:'weapon' },
  { id:'stream-bandolier-3', name:'Stream-Bandolier Jewel [3]', skill:'Water Attack', lv:3, skill2:'Tetrad Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-crit-elem-3', name:'Stream-Crit Elem Jewel [3]', skill:'Water Attack', lv:3, skill2:'Critical Element', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-enhancer-3', name:'Stream-Enhancer Jewel [3]', skill:'Water Attack', lv:3, skill2:'Power Prolonger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-focus-3', name:'Stream-Focus Jewel [3]', skill:'Water Attack', lv:3, skill2:'Focus', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-guardian-3', name:'Stream-Guardian Jewel [3]', skill:'Water Attack', lv:3, skill2:'Offensive Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-handicraft-3', name:'Stream-Handicraft Jewel [3]', skill:'Water Attack', lv:3, skill2:'Handicraft', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-ironwall-3', name:'Stream-Ironwall Jewel [3]', skill:'Water Attack', lv:3, skill2:'Guard', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-ko-3', name:'Stream-KO Jewel [3]', skill:'Water Attack', lv:3, skill2:'Slugger', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-opener-3', name:'Stream-Opener Jewel [3]', skill:'Water Attack', lv:3, skill2:'Opening Shot', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-precise-3', name:'Stream-Precise Jewel [3]', skill:'Water Attack', lv:3, skill2:'Ballistics', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-quickswitch-3', name:'Stream-Quickswitch Jewel [3]', skill:'Water Attack', lv:3, skill2:'Rapid Morph', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-rzr-sharp-3', name:'Stream-Rzr Sharp Jewel [3]', skill:'Water Attack', lv:3, skill2:'Razor Sharp', lv2:1, slot:3, rarity:6, type:'weapon' },
  { id:'stream-shield-3', name:'Stream-Shield Jewel [3]', skill:'Water Attack', lv:3, skill2:'Guard Up', lv2:1, slot:3, rarity:6, type:'weapon' },
];

if (typeof module !== 'undefined') module.exports = DECORATIONS;
